// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvroypbyucljliikrsij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2cm95cGJ5dWNsamxpaWtyc2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMDI2OTQsImV4cCI6MjA1NDc3ODY5NH0.82_0jW7oYGrjF7QomwtPacsCHLsh_qCqPnGWuKeLlIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);